### PR TITLE
Plugin compatibility for sonar version 7.7 and cmd timeout annotate parameterizable

### PR DESCRIPTION
**Pull request by aumoraes**
Plugin Compatibility for sonar version 7.7;
Feature cmd editable timeout, annotate command, parameterizable field;
Change launcher 'lscm' to 'fec' ( lscm calls fec, under the table ).

### CODE REVIEW

**Comment by henryju** [comment]
Hi @aumoraes . AFAIK this plugin is not maintained anymore by SonarSource. If you want to take it, feel free to open a thread on our community forum (cc @ganncamp ).

**Comment by troosan** [comment]
@aumoraes If it's OK with you I'm going to create another pull request with just the parametrisable timeout.

**Comment by aumoraes** [comment]
@troosan It would be nice.
Could please add my name on pom.xml as developer contributor?

**Comment by troosan** [comment]
merged in PR #17

**Pull request closed without merging**
